apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-identities-allow-all
  namespace: default
data:
  values.yaml: |
    e4kmqtt:
      authenticationMethods:
        - method: allowall
    e4kspiffe:
      server:
        jwt:
          ttl: 30